version: '3.8'
services:
  mongodb:
    container_name: maoudia-mongodb
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "15015"]
    image: mongo:7.0.2
    environment:
      - MONGO_INITDB_DATABASE=test
    networks:
      - mongodb-network
    ports:
      - 15015:15015
    volumes:
      - ./data/db:/data/db

  mongo-express:
    container_name: maoudia-mongo-express
    image: mongo-express:1.0.0
    depends_on:
      - mongodb
    networks:
      - mongodb-network
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://maoudia-mongodb:15015/?replicaSet=rs0
    ports:
      - 1515:8081
    volumes:
      - ./data/mongodb:/data/mongodb

  product-api:
    container_name: maoudia-product-api
    image: clue/json-server:latest
    ports:
      - 1519:80
    volumes:
      - ./data/product/db.json:/data/db.json

networks:
  mongodb-network:
    driver: bridge
